### ISSUE TITLE
Add via storyboard

### ISSUE THREAD

**Issue by orium-dev** [melloskitten/pikko#28]
Is it possible to add pikko view storyboard? I tried and its just white box
If not, could you please add more samples how to position pikko on view? I tried with constaints and it doesn't respond to clicks

**Comment by melloskitten** [comment]
We will add both of your requests to our list of issues and try to integrate them ASAP 👍 
Thanks for the feature request!

**Comment by melloskitten** [comment]
@orium-dev you can now add autoconstraints programmatically as well as pikko via storyboard. you can find an explanation for that in the readme. enjoy :)
